version: '3.3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.local
    ports:
      - "8081:80"       # Web UI
      - "443:443"       # HTTPS (optional)
      - "2222:22"         # SSH for Git
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

